import type { Metadata } from 'next';
import { Baloo_Bhaijaan_2 } from 'next/font/google';
import './globals.css';
import ToasterProvider from './_providers/ToasterProvider';
import AuthContextProvider from './_providers/AuthContextProvider';

const inter = Baloo_Bhaijaan_2({
  subsets: ['latin'],
  weight: ['400', '500', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ToasterProvider>
          <AuthContextProvider>{children}</AuthContextProvider>
        </ToasterProvider>
      </body>
    </html>
  );
}
